"""
scripts/export_models.py
------------------------
Verifies that trained models exist in models/ and are ready for inference.

Models are saved DIRECTLY during training by:
  - train_model.py      → models/kmeans_model.pkl + models/scaler.pkl
  - train_classifier.py → models/rf_model.pkl
  - scripts/save_scaler.py (if scaler.pkl is missing)

This script validates those files and optionally attempts to pull the
latest versions from the remote MLflow server if any are missing.

Usage:
    python scripts/export_models.py
"""

import os
import sys
import socket
import logging
import joblib

logging.basicConfig(
    format="%(asctime)s | %(levelname)s | %(message)s",
    level=logging.INFO,
)
logger = logging.getLogger(__name__)

TRACKING_URI  = os.getenv("MLFLOW_TRACKING_URI", "mlruns")
EXPERIMENT    = os.getenv("MLFLOW_EXPERIMENT",   "customer")
MODELS_DIR    = "models"

REQUIRED_MODELS = {
    "kmeans_model.pkl":  ("Step4_KMeans_Clustering",      "kmeans_model"),
    "rf_model.pkl":      ("Step6_RandomForest_Classifier", "random_forest_model"),
    "scaler.pkl":        None,   # generated by save_scaler.py — no MLflow artifact
}

os.makedirs(MODELS_DIR, exist_ok=True)


# ─────────────────────────────────────────────────────────────────────────────
# TCP probe (2-second timeout)
# ─────────────────────────────────────────────────────────────────────────────

def _reachable(uri: str) -> bool:
    try:
        from urllib.parse import urlparse
        p = urlparse(uri)
        with socket.create_connection((p.hostname or "localhost", p.port or 80), timeout=2):
            return True
    except OSError:
        return False


# ─────────────────────────────────────────────────────────────────────────────
# MLflow fetch (only called when a file is missing)
# ─────────────────────────────────────────────────────────────────────────────

def _fetch_from_mlflow(run_name: str, artifact_path: str, out_path: str) -> bool:
    """Try to pull model from remote MLflow server. Returns True on success."""
    if not _reachable(TRACKING_URI):
        logger.warning("  MLflow server not reachable: %s", TRACKING_URI)
        return False
    try:
        import mlflow
        import mlflow.sklearn
        mlflow.set_tracking_uri(TRACKING_URI)
        client = mlflow.tracking.MlflowClient()
        exp = client.get_experiment_by_name(EXPERIMENT)
        if exp is None:
            logger.warning("  Experiment '%s' not found on remote server.", EXPERIMENT)
            return False
        # Support both old tag filter and new attribute filter
        for flt in [f"run_name = '{run_name}'",
                    f"tags.mlflow.runName = '{run_name}'"]:
            runs = client.search_runs(
                [exp.experiment_id], filter_string=flt,
                order_by=["start_time DESC"], max_results=1,
            )
            if runs:
                break
        if not runs:
            logger.warning("  No run '%s' found on remote server.", run_name)
            return False
        run_id = runs[0].info.run_id
        uri    = f"runs:/{run_id}/{artifact_path}"
        logger.info("  Fetching from MLflow: %s", uri)
        model  = mlflow.sklearn.load_model(uri)
        joblib.dump(model, out_path)
        logger.info("  Saved → %s", out_path)
        return True
    except Exception as exc:
        logger.warning("  MLflow fetch failed: %s", exc)
        return False


# ─────────────────────────────────────────────────────────────────────────────
# Main
# ─────────────────────────────────────────────────────────────────────────────

def main():
    all_ok   = True
    missing  = []

    for filename, mlflow_info in REQUIRED_MODELS.items():
        path = os.path.join(MODELS_DIR, filename)

        if os.path.exists(path) and os.path.getsize(path) > 0:
            size_kb = os.path.getsize(path) // 1024
            logger.info("  %-30s  OK  (%d KB)", filename, size_kb)
        else:
            logger.warning("  %-30s  MISSING", filename)
            missing.append((filename, path, mlflow_info))

    if missing:
        logger.info("Attempting to recover %d missing file(s) from MLflow...", len(missing))
        for filename, path, mlflow_info in missing:
            if mlflow_info is None:
                # scaler — regenerate from save_scaler.py
                logger.info("  %s: running save_scaler.py to regenerate...", filename)
                import subprocess, sys as _sys
                r = subprocess.run([_sys.executable, "scripts/save_scaler.py"])
                if r.returncode != 0 or not os.path.exists(path):
                    logger.error("  Failed to regenerate %s", filename)
                    all_ok = False
            else:
                run_name, artifact_path = mlflow_info
                ok = _fetch_from_mlflow(run_name, artifact_path, path)
                if not ok:
                    logger.error(
                        "  Could not recover %s. "
                        "Ensure the pipeline ran successfully before exporting.", filename
                    )
                    all_ok = False

    # Final summary
    logger.info("─" * 55)
    for filename in REQUIRED_MODELS:
        path    = os.path.join(MODELS_DIR, filename)
        exists  = os.path.exists(path) and os.path.getsize(path) > 0
        size_kb = os.path.getsize(path) // 1024 if exists else 0
        status  = f"✅  {size_kb} KB" if exists else "❌  MISSING"
        logger.info("  %-30s  %s", filename, status)
    logger.info("─" * 55)

    if not all_ok:
        logger.error("Some models are missing. Cannot proceed with deployment.")
        sys.exit(1)

    logger.info("All models present and ready for inference.")


if __name__ == "__main__":
    main()
